Bugfix/C4R-1367
code4romania/centrucivic pull request #28
Opened 2022-12-23 12:43 UTC by AndreeaMariaP

Bug [C4R-1367](https://wearetribus.atlassian.net/browse/C4R-1367)

2022-12-23 12:54 UTC, radulescuandrew requested changes

2022-12-23 12:54 UTC, radulescuandrew commented on src/common/components/service-content/ServiceContent.tsx
> +        <h3 className="font-titilliumBold text-2xl break-all">{service.name}</h3>
Ar trebui sa punem `break-word` nu `break-all`

2022-12-23 13:05 UTC, AndreeaMariaP commented on src/common/components/service-content/ServiceContent.tsx
> +        <h3 className="font-titilliumBold text-2xl break-all">{service.name}</h3>
true, modific

2022-12-28 08:23 UTC, radulescuandrew approved these changes

2022-12-28 08:25 UTC, merged